global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: "postgres"
    static_configs:
      - targets: ["postgres-exporter:9187"]

  - job_name: "backend"
    static_configs:
      - targets: ["backend:8081"]

  - job_name: "keycloak"
    static_configs:
      - targets: ["keycloak:9990"]
    metrics_path: "/metrics"

  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]