name: Go Compositional Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Позволяет запускать вручную через UI GitHub

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Run gosec (Security Analysis)
        run: |
          go install github.com/securego/gosec/v2/cmd/gosec@latest
          gosec ./... 2>&1 | tee gosec-report.txt

      - name: Run staticcheck (Static Analysis)
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          staticcheck ./... 2>&1 | tee staticcheck-report.txt

      - name: Run govulncheck (Vulnerability Check)
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          govulncheck ./... 2>&1 | tee vulncheck-report.txt

      - name: Upload reports as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: analysis-reports
          path: |
            gosec-report.txt
            staticcheck-report.txt
            vulncheck-report.txt
