name: Notify Bot
on: [push]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v34
        with:
          separator: ","  # Используем запятую как разделитель
          
      - name: Notify Telegram Bot
        run: |
          # Формируем ОЧЕНЬ простое сообщение
          MESSAGE="FILES:${{ steps.changed-files.outputs.all_changed_files }}"
          curl -s -X POST "https://api.telegram.org/bot8139397748:AAG3ZSOdCMlKNrIZ9a3q8bhMx3LLwSS8oIc/sendMessage" \
            -d "chat_id=451796774" \
            -d "text=$MESSAGE"
